# Generated by Django 5.0.2 on 2024-02-28 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book_DB',
            fields=[
                ('Bookno', models.IntegerField(primary_key='Bookno', serialize=False)),
                ('Bookname', models.CharField(max_length=20)),
                ('author', models.EmailField(max_length=254)),
                ('pageno', models.DateField()),
                ('language', models.IntegerField()),
            ],
        ),
    ]
